import type {
  BUTTON_MODIFIER,
  BUTTON_PROPORTION,
  BUTTON_SEVERITY,
} from 'common/constants/buttonConstants'

export type BUTTON_PROPORTION_TYPE =
  | BUTTON_PROPORTION.SMALL
  | BUTTON_PROPORTION.LARGE
  | BUTTON_PROPORTION.MEDIUM
export type BUTTON_SEVERITY_TYPE = BUTTON_SEVERITY.DANGER | BUTTON_SEVERITY.SUCCESS

export type BUTTON_MODIFIER_TYPE =
  | BUTTON_MODIFIER.PRIMARY
  | BUTTON_MODIFIER.SECONDARY
  | BUTTON_MODIFIER.TERTIARY
  | BUTTON_MODIFIER.DEFAULT
