import type { FORM_CONTROL_TYPE } from 'common/constants/formControlConstants'

export type TYPE_FORM_CONTROL =
  | FORM_CONTROL_TYPE.INPUT
  | FORM_CONTROL_TYPE.CHECKBOX
  | FORM_CONTROL_TYPE.TEXTAREA
  | FORM_CONTROL_TYPE.RADIO
  | FORM_CONTROL_TYPE.SELECT
  | FORM_CONTROL_TYPE.SWITCH
  | FORM_CONTROL_TYPE.UPLOAD
